### ISSUE TITLE
Versioning dctap-python

### ISSUE THREAD

**Issue by tombaker** [dcmi/dctap-python#12]
@nishad The current version number is 0.2, but that seems low. Can you point me to guidelines we might follow?

**Comment by nishad** [comment]
SemVer [1] is preferred. CalVer is an alternative, but I prefer SemVer for our use-case. If we are planning to adhere to SemVer, then 0.2 can be minor and major, so it doesn't break anything. 

Along with versioning, I strongly advocate for maintaining a `CHANGELOG.md` as per Keep A Changelog [3] specification.

[1] https://semver.org/
[2] https://calver.org/
[3] https://keepachangelog.com

**Comment by tombaker** [comment]
@nishad I want to become more disciplined about keeping a change log and versioning once DCTAP is presented to LD4 next week. I also want to improve the granularity and messages for my commits (do you have a good link to a style guide?) and optimize the pace and content of my pull requests (do you prefer to be asked for a review only for larger changes? Better focused and frequent, or broad and infrequent?).

In the meantime, we should make sure that by Friday, 23 January, the PyPI version is up-to-date with the latest version on Github. Currently, the version number (0.2.2) is recorded in [`__init__.py`](https://github.com/dcmi/dctap-python/blob/main/dctap/__init__.py) and [`cli.py`](https://github.com/dcmi/dctap-python/blob/main/dctap/cli.py#L20) -- not, for example, in [pyproject.toml](https://github.com/dcmi/dctap-python/blob/main/pyproject.toml). Does PyPI read `__init__.py`?

If I wanted to update PyPI right now (would you suggest it?), I guess I would need to change the version (0.2.3).

Good idea?

**Comment by nishad** [comment]
There are a lot of examples and articles about the commit message practices. I am no that keen on following any conventions, though. Usually, I stick with something that mutually works for all collaborators. However, Linus's explanation of commit messages is popular and worth a read [1].

Reviews are good if something is suggestive and still under discussion. Usually, the collaborators will reach a convenient consensus about review requests at some point. But as a rule of thumb, for the projects with a small group of known collaborators with commit access, I request the project maintainers to review the PR to ensure that they are aware and agree with the changes. If I don't have commit access to the repo,  in most cases, I issue a PR without a review request and often request a review if the PR is updated based on the maintainer's feedback. 

I prefer the version number to be maintained in a 'single source of truth' [2] and reuse it wherever required. So `__version__` from `__init__.py` can be used everywhere else, including `cli.py`.

Since PyPI is our release channel, feel free to release all versioned tags from GitHub. The simple guideline is -- "release early, release often" [3].

[1] https://github.com/torvalds/subsurface-for-dirk/blob/a48494d2fbed58c751e9b7e8fbff88582f9b2d02/README#L88
[2] https://en.wikipedia.org/wiki/Single_source_of_truth
[3] https://en.wikipedia.org/wiki/Release_early,_release_often

**Comment by tombaker** [comment]
Resolved - we are using SemVer.
