### ISSUE TITLE
Element aliases causing error in dctap.yaml?

### ISSUE THREAD

**Issue by philbarker** [dcmi/dctap-python#18]
Running the latest version of dctap with a dctap.yml that sets an element alias causes the error
`Valid DCTAP CSV must have a 'propertyID' column.`

to repeat use: 
dctap.yaml:
```
### dctap configuration file (in YAML format)
extra_statement_template_elements:
 - severity

element_aliases:
     "Mand": "mandatory"
     "Rep": "repeatable"
```

tap.csv:
```
shapeID,propertyID,propertyLabel,Mand,Rep,valueNodeType,valueDataType,valueConstraint,valueConstraintType,valueShape,note,severity
BookShape,dct:title,Title,TRUE,FALSE,Literal,rdf:langString,,,,,Violation
BookShape,dct:creator,Author,FALSE,TRUE,IRI BNODE,,,,AuthorShape,,Warning
BookShape,sdo:isbn,ISBN-13,FALSE,FALSE,Literal,xsd:string,^(\\d{13})?$,pattern,,"Just the 13 numbers, no spaces or separators.",Violation
BookShape,rdf:type,Type,TRUE,FALSE,IRI,,sdo:Book,,,,Warning
AuthorShape,rdf:type,Type,TRUE,TRUE,IRI,,foaf:Person,,,,Warning
AuthorShape,foaf:givenName,Given name,FALSE,TRUE,Literal,xsd:string,,,,,Warning
AuthorShape,foaf:familyName,Family name,FALSE,TRUE,Literal,xsd:string,,,,,Warning
```

Removing the element_alias block from dctap.yaml fixes the error message.

**Comment by tombaker** [comment]
@philbarker The program currently generates a "starter" config file in which everything is commented out, including the example element aliases.

So you were able to fix the problem by removing an element alias for 'propertyID'?

**Comment by philbarker** [comment]
No, there never was an element alias for `propertyID`. As soon as I add those aliases to the starter config file I get the error.

I plan to not use them, I can manage without.

Are you able to reproduce the behaviour with those files?

**Comment by tombaker** [comment]
@philbarker 
> Are you able to reproduce the behaviour with those files?

Yes, I get the same behavior, even if I reduce `tap.csv` down to:
```
propertyID
dct:title
```
The problem does seem to lie with the config file, though it parses correctly on [yaml-online-parser.appspot.com](https://yaml-online-parser.appspot.com/). Oddly, when I edit `dctap.yaml` with vim, to comment out the last three lines (starting with `element_aliases:`), it indents those three lines, which is surprising.

**Comment by tombaker** [comment]
@philbarker - see https://bit.ly/3N6UMho which confirms that the YAML parses correctly. Will try to get to the bottom of this...

**Comment by tombaker** [comment]
@philbarker The problem was that when element aliases were asserted in the config file, and the dictionary created from the config file was used to update the config dictionary, those aliases were not being added to, but rather _replacing_ (clobbering) the existing default aliases -- the ones generated automatically so that element names can be case-insensitive and contain spaces. I was missing this bug because of insufficient tests.

The solution is simple -- to change the optional setting in the config file from `element_aliases` to `extra_element_aliases` which, if found configured, will be added to the automatically generated default aliases.

I am working on a branch and want to make sure this has proper tests in place before merging.

Thank you for catching this!

**Comment by tombaker** [comment]
@philbarker In the meantime, if no element aliases are declared in the config file, everything should work properly, as you already discovered.

**Comment by tombaker** [comment]
Closing this issue - solved by creating `extra_element_aliases` as an additional configuration setting.
